language: php

dist: precise

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - >
    if [[ "$TYPO3" = *"dev"* ]]; then
      composer config minimum-stability dev;
      composer config prefer-stable true;
    fi
  - if [ "$MASK" != "" ]; then composer require mask/mask="$MASK" --no-update; fi
  - composer require typo3/cms="$TYPO3"
  - mkdir -p .Build/Web/typo3conf/ext/
  - if [ ! -L .Build/Web/typo3conf/ext/mask_export ]; then ln -snvf ../../../../. .Build/Web/typo3conf/ext/mask_export; fi
  - export TYPO3_PATH_ROOT=$PWD/.Build/Web
  - export typo3DatabaseName=typo3
  - export typo3DatabaseHost=localhost
  - export typo3DatabaseUsername=root
  - export typo3DatabasePassword=

script:
  - >
    echo;
    echo "Running functional tests";
    echo;
    echo;
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}';

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

jobs:
  fast_finish: true
  allow_failures:
    - env: TYPO3=^8.7 MASK="dev-master as 3.0.0"
    - env: TYPO3="8.x-dev as 8.7.0"
    - env: TYPO3="8.x-dev as 8.7.0" MASK="dev-master as 3.0.0"
    - env: TYPO3="7.x-dev as 7.6.0"
  include:
    - stage: test
      php: 7.2
      env: TYPO3="8.x-dev as 8.7.0"
    - stage: test
      php: 7.2
      env: TYPO3="8.x-dev as 8.7.0" MASK="dev-master as 3.0.0"
    - stage: test
      php: 7.2
      env: TYPO3=^8.7
    - stage: test
      php: 7.2
      env: TYPO3=^8.7 MASK="dev-master as 3.0.0"
    - stage: test
      php: 7.2
      env: TYPO3=^7.6
    - stage: test
      php: 7.2
      env: TYPO3="7.x-dev as 7.6.0"
    - stage: test
      php: 7.1
      env: TYPO3="8.x-dev as 8.7.0"
    - stage: test
      php: 7.1
      env: TYPO3="8.x-dev as 8.7.0" MASK="dev-master as 3.0.0"
    - stage: test
      php: 7.1
      env: TYPO3=^8.7
    - stage: test
      php: 7.1
      env: TYPO3=^8.7 MASK="dev-master as 3.0.0"
    - stage: test
      php: 7.1
      env: TYPO3=^7.6
    - stage: test
      php: 7.1
      env: TYPO3="7.x-dev as 7.6.0"
    - stage: test
      php: 7.0
      env: TYPO3="8.x-dev as 8.7.0"
    - stage: test
      php: 7.0
      env: TYPO3="8.x-dev as 8.7.0" MASK="dev-master as 3.0.0"
    - stage: test
      php: 7.0
      env: TYPO3=^8.7
    - stage: test
      php: 7.0
      env: TYPO3=^8.7 MASK="dev-master as 3.0.0"
    - stage: test
      php: 7.0
      env: TYPO3=^8.7
    - stage: test
      php: 7.0
      env: TYPO3=^7.6
    - stage: test
      php: 7.0
      env: TYPO3="7.x-dev as 7.6.0"
    - stage: test
      php: 7.0
      env: TYPO3=^7.6
    - stage: test
      php: 5.6
      env: TYPO3=^7.6
    - stage: test
      php: 5.6
      env: TYPO3="7.x-dev as 7.6.0"
    - stage: test
      php: 5.5
      env: TYPO3=^7.6
    - stage: test
      php: 5.5
      env: TYPO3="7.x-dev as 7.6.0"

    - &code
      stage: code analysis
      php: 7.1
      env: TYPO3="8.x-dev as 8.7.0"
      install:
        - composer require typo3/cms="$TYPO3" phpstan/phpstan="^0.9"
      script:
        - .Build/bin/phpstan analyse --level 5 ext_tables.php Classes Tests
    - <<: *code
      env: TYPO3="7.x-dev as 7.6.0"
