language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3="dev-master as 8.2.0" PHPUNIT_TESTS=yes
    - php: 7.1
      env: TYPO3="8.6.1 as 8.2.0" PHPUNIT_TESTS=yes PHP_LINT=yes
    - php: 7.1
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes
    - php: 7.0
      env: TYPO3="dev-master as 8.2.0" PHPUNIT_TESTS=yes
    - php: 7.0
      env: TYPO3="8.6.1 as 8.2.0" PHPUNIT_TESTS=yes PHP_LINT=yes
    - php: 7.0
      env: TYPO3="8.6.1 as 8.2.0" CODE_ANALYSIS=yes
    - php: 7.0
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes
    - php: 7.0
      env: TYPO3=^7.6 CODE_ANALYSIS=yes
    - php: 5.6
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes PHP_LINT=yes
    - php: 5.5
      env: TYPO3=^7.6 PHPUNIT_TESTS=yes PHP_LINT=yes
  allow_failures:
    - env: TYPO3="dev-master as 8.2.0" PHPUNIT_TESTS=yes

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require typo3/cms="$TYPO3"
  - git checkout composer.json
  - mkdir -p .Build/Web/typo3conf/ext/
  - if [ ! -L .Build/Web/typo3conf/ext/mask_export ]; then ln -snvf ../../../../. .Build/Web/typo3conf/ext/mask_export; fi
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    if [ "$PHPUNIT_TESTS" == "yes" ]; then
      echo;
      echo "Running functional tests";
      echo;
      echo;
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}';
    fi

  - >
    if [ "$PHP_LINT" == "yes" ]; then
      echo;
      echo "Running php lint";
      echo;
      echo;
      find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
    fi

  - >
    if [ "$CODE_ANALYSIS" == "yes" ]; then
      composer require typo3/cms="$TYPO3" phpstan/phpstan="^0.6";
      git checkout composer.json;
      .Build/bin/phpstan analyse --level 5 ext_tables.php Classes Tests;
    fi
